---
- name: "check for previously completed run"
  stat:
    path: /tmp/ansible-base-play-complete
  register: is_already_configured

- name: "write completed run"
  file:
    path: /tmp/ansible-base-play-complete
    state: touch
    mode: "u=rw,g=r,o=r"
  when: mark_run_complete == True

- block:
    - name: "exit early"
      debug:
        msg: "marker file detected, terminating early"

    - meta: end_play
  when:
    - is_already_configured.stat.exists == True
