---
- hosts: "{{ variable_host | default('centos') }}"
  gather_facts: yes
  roles:
    - { role: ami }
    - { role: package-management }
    - { role: generic }
    - { role: os-hardening,
        os_desktop_enable: false,
        os_security_packages_list: ['xinetd','inetd','ypserv','telnet-server','rsh-server'] }
    - { role: ssh-hardening }
    - { role: audit-hardening }

- hosts: hadoop_ambari_nodes
  gather_facts: yes
  roles:
    - { role: base-role-fixes }
